language: php
matrix:
  include:
    - php: 7.2
    - php: 7.4

sudo: false
before_install:
  - export NEOS_TARGET_VERSION=5.3
  - cd ..
  - git clone https://github.com/neos/neos-base-distribution.git -b ${NEOS_TARGET_VERSION}
  - cd neos-base-distribution
  - composer require --no-update --no-interaction punktde/flow-zoom-api
install:
  - composer install --no-interaction
  - cd ..
  - rm -rf neos-base-distribution/Packages/Application/PunktDe.Zoom.Api
  - mv archivist neos-base-distribution/Packages/Application/PunktDe.Zoom.Api
  - cd neos-base-distribution
script:
  - bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/PunktDe.Zoom.Api/Tests/Unit
  - bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/PunktDe.Zoom.Api/Tests/Functional
