PunktDe:
  Zoom:
    Api:
      clientId: '%env:ZOOM_CLIENT_ID%'
      clientSecret: '%env:ZOOM_CLIENT_SECRET%'
      baseUri: '%env:ZOOM_BASE_URI%'
      defaults:
        channel: default
        locale: de_DE
